### ISSUE TITLE
Tags at start of text apply throughout text.

### ISSUE THREAD

**Issue by graham-perks-snap** [psharanda/Atributika#1]
Starting text with a tag applies that tag throughout, even though there is a matching end tag.

"<b>Save $1.00</b> on <b>any</b> order!"  comes out all bold.

"Save <b>$1.00</b> on <b>any</b> order!" correctly bolds only the two sections.

With this call:

                let desc = Atributika(text: text,
                                      styles: [
                                        "b" : [.font( UIFont.boldSystemFont(ofSize: 14))]
                    ],
                                      baseStyle: [
                                        .font( UIFont.systemFont(ofSize: 14)), .foregroundColor(UIColor.red)
                    ])
                    .buildAttributedString()

**Comment by psharanda** [comment]
Could you provide the value for 'text' variable?

**Comment by graham-perks-snap** [comment]
I tried, it got HTML'd :)  

Bad: `"<b>Save $1.00</b> on <b>any</b> order!"`
Good: `"Save <b>$1.00</b> on <b>any</b> order!"`

**Comment by psharanda** [comment]
Hm, I was not able to reproduce. I put a test case (AtributikaTests.testIssue1) with the same data you did provide and it works just fine. Probably there is something else. Do you put this string directly or take it from some source? If you take it from somewhere else you must be sure that <,>, & are escaped.

**Comment by graham-perks-snap** [comment]
Let me have another try.

**Comment by graham-perks-snap** [comment]
OK, totally my fault! I had my fonts mixed up, bold of one looks just like regular of the other... so it looked like the whole thing was bold. In recompense I offer a new unit test around 'baseStyle', which otherwise didn't have much testing around it. Thanks for a very nice library :)

**Comment by psharanda** [comment]
You are welcome :)
