### ISSUE TITLE
Can I convert NSAttributed string to HTML String?

### ISSUE THREAD

**Issue by vinayakparmar92** [psharanda/Atributika#10]
@psharanda Is there any way I can convert the NSAttributedString that I received using this library back again to HTML String?

**Comment by psharanda** [comment]
It is not possible to restore original HTML from NSAttributedString, because that string doesn't have the info where from attributes come. Though Atributika uses intermediate structure `AttributedText` which contains 'detections' array, where you can find all the things were detected (with ranges and type of detection). Using it you can restore original HTML. But guess it will be easier just to save original HTML string.

**Comment by vinayakparmar92** [comment]
The HTML string here is basically text from UITextView. In case I save the string then it will be very difficult to keep saved HTML string and UITextView text in sync if the user edits the textview.

**Comment by vinayakparmar92** [comment]
I tried using the Native way using NSDocumentTypeDocumentAttribute, but it adds a lot of unnecessary CSS and HTML stuff to the string

**Comment by psharanda** [comment]
Do you mean that you write HTML in UITextView?

**Comment by vinayakparmar92** [comment]
I have to send to server an HTML text. It has got tagging links on some word(<a> tag). Basically I am implementing user tagging in textview. So when user choose a user from the autocomplete results, I will replace that word with an attributed text which I will get from your library. 

e.g:  Lets say I my UITextView is textview, then
```
print(savedHTMLString) \\ Test user tagging <a href=\“http://app.babychakra.com/user/40770\“>Saravanan</a>
print(textview.text) \\ Test user tagging Saravanan
print(textview.attributedText) \\ Test user tagging Saravanan(highlighted word)
```

**Comment by psharanda** [comment]
You should not rely on textview.attributedText for storing state. When you adding user from autocomplete, you need to save range for it explicitly in some external array. Your textview needs to render state, not store it. Also Atributika might be not needed at all for your case.

**Comment by vinayakparmar92** [comment]
I totally got the solution that you recommending. Seems like a better idea. Will try doing that. Thanks for the update
