### ISSUE TITLE
Text clipped 

### ISSUE THREAD

**Issue by Kendokai** [psharanda/Atributika#100]
I have copied from example and just change text , the text got clipped even I increase height of the label.

![Screen Shot 2019-11-07 at 11 14 14 AM](https://user-images.githubusercontent.com/8243358/68359796-f56fa400-014f-11ea-8525-cba0aaf5a098.png)

**Comment by psharanda** [comment]
Please take a look at latest release 4.9.1, and let me know if you still have this problem. Some critical autolayout related bug was fixed
