### ISSUE TITLE
Paragraph tag (<p>) doesn't start from new line

### ISSUE THREAD

**Issue by tarun-personatech** [psharanda/Atributika#106]
The below text with paragraph tags doesn't start from new line on every <p> tag.

`<p> The first line of the text.</p><p>This second line should start a new paragraph. but it doesn't</p>`

 How can I get it working?

**Comment by philhinco** [comment]
When calling `.style()` on the string you want to style, pass an array of `TagTransformer` like this:

```swift
let transformers = [TagTransformer(tagName: "p", tagType: .start, replaceValue: "\n")]
//More style definitons, etc
yourString.style([tag1, tag2], transformers: transformers]
```

This `TagTransformer` adds a `\n` to the start of a paragraph tag. If you'd prefer it to always add one at the end, just replace the tagType with `.end`.

TagTransformer has one predefined transformer, `TagTransformer.brTransformer`, which transforms a `<br>` into a `\n`

**Comment by joaomvfsantos** [comment]
Picking up on this one to not open a new issue. Based on @philhinco solution, is there a way to apply the replace value with a new line char, on every paragraph, except the last one? For example if I have: 
```html
<p>One!</p>
<p>Two!</p>
<p>Three!</p>
```
There would be a newline char at the end of One! and at the end of Two!, but not at the end of Three!

**Comment by philhinco** [comment]
@joaomvfsantos You could probably use the `tuner:` argument of the `style()` call, though I‘m not sure how you could find out which tag is the last of its kind.

**Comment by pcr910303** [comment]
@joaomvfsantos I'm pretty sure I'm too late, and the solution is pretty trivial, but for people who are searching: this code works.

```swift
extension TagTransformer {
    static func pTransformer() -> TagTransformer {
        var isStart = true
        let transformer = TagTransformer(tagName: "p", tagType: .start) { _ in
            if isStart {
                isStart = false
                return ""
            } else {
                return "\n"
            }
        }
        return transformer
    }
}
```

Then instantiate the transformer with `.pTransformer()`. (It can't be a static var like `.brTransformer` as it's stateful.)

**Comment by andersonalex** [comment]
A great workaround for the "don't apply this to the first/last tag" problem is to just trim whitespace from the final attributedString. There are some solutions for that here: https://stackoverflow.com/questions/34081197/how-to-trimremove-white-spaces-from-end-of-a-nsattributedstring
