### ISSUE TITLE
Li identation

### ISSUE THREAD

**Issue by Kijubei** [psharanda/Atributika#107]
Hi,

First off, great package you made! I really like it so far. Now to my problem:

I would like to add a li-style to my string and everyting works well, except the indentation when a line break occours.

Example how it looks:

(imagine these were regular dots, like bellow)
. line 1
. line 2
. line 3 is very very very very very very
very long

How it should look like:
* line 1
* line 2
* line 3 is very very very very very very
very long

When the long line breaks it start at the same identation as the dot, which is not how I want it. I tried to solve it with a NSMutableParagraphStyle, but it is not applicable as far as I see it. Is there a way to do this?

Thanks in advance!

**Comment by psharanda** [comment]
Hi, 
Thanks for your support!
I found this answer with example of code for such lists https://stackoverflow.com/a/46952096/611360

**Comment by psharanda** [comment]
```
func stringWithIndentedList() -> NSAttributedString {
    let bullet = "• "
    let transformers: [TagTransformer] = [
        TagTransformer.brTransformer,
        TagTransformer(tagName: "li", tagType: .start, replaceValue: bullet),
        TagTransformer(tagName: "li", tagType: .end, replaceValue: "\n")
    ]

    let listItemFont = UIFont.systemFont(ofSize: 12)
    let indentation: CGFloat = (bullet as NSString).size(withAttributes: [NSAttributedStringKey.font: listItemFont]).width

    let paragraphStyle = NSMutableParagraphStyle()
    paragraphStyle.tabStops = [NSTextTab(textAlignment: .left, location: indentation, options: [NSTextTab.OptionKey: Any]())]
    paragraphStyle.defaultTabInterval = indentation
    paragraphStyle.headIndent = indentation

    let li = Style("li")
        .font(listItemFont)
        .paragraphStyle(paragraphStyle)

    return "TODO:<br><li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras a mollis mauris. Cras non mauris nisi. Ut turpis tellus, pretium sed erat eu, consectetur volutpat nisl. Praesent at bibendum ante</li><li>Vestibulum ornare dui ut orci congue placerat. Cras a mollis mauris. Cras non mauris nisi. Ut turpis tellus, pretium sed erat eu, consectetur volutpat nisl. Praesent at bibendum ante</li><li>Nunc et tortor vulputate, elementum quam at, tristique nibh. Cras a mollis mauris. Cras non mauris nisi. Ut turpis tellus, pretium sed erat eu, consectetur volutpat nisl. Praesent at bibendum ante</li>"
        .style(tags: li, transformers: transformers)
        .styleAll(Style.font(.boldSystemFont(ofSize: 14)))
        .attributedString
}
```

**Comment by Kijubei** [comment]
`    let li = Style("li")
        .font(listItemFont)
        .paragraphStyle(paragraphStyle)
`

Omg, it was that simple! 

Thank you for the fast answer. It works exactly how I want it. Keep up the good work!
