### ISSUE TITLE
UnOrdered and Ordered list are not getting applied together.

### ISSUE THREAD

**Issue by ankitthakur** [psharanda/Atributika#111]
Hi team,

We are receiving html string from server, where multiple tags are added like bold, italic, strikethrough, smilies, ordered and unordered list.
And when I try to apply all styles on the string, then it's giving compile time error.

![Screenshot 2020-03-12 at 2 45 46 PM](https://user-images.githubusercontent.com/75362/76506990-0c156700-6472-11ea-8bd1-1ee8bea48f0a.png)

**Comment by psharanda** [comment]
Hi,
`style(tags:)` method is a `String` method, also it returns value of `AttributedText` type which doesn't have such method. In other words you can't chain several calls of `style(tags:)` methods. This is done intentionally, since html parsing makes sense to run just once.
