### ISSUE TITLE
Command failed due to signal: Segmentation fault: 11

### ISSUE THREAD

**Issue by MihauMihau** [psharanda/Atributika#12]
When trying to compile I got an Xcode error "Command failed due to signal: Segmentation fault: 11" when trying to use .style on a String.

**Comment by psharanda** [comment]
Something wrong with your setup, because it works for me and others.
Please provide your xcode, swift and atributika versions. 
Do you use CocoaPods or Carthage?
Did you try to clean DerivedData?

**Comment by MihauMihau** [comment]
Hey, I use CocoaPods, Xcode 9.0, project is in Swift 3.2. Maybe it hast to be on 4.0? Atributika 4.1.1. Is there a version for Swift 3.2? Didn't clear the DerivedData.

**Comment by psharanda** [comment]
Hey,
Yes I have the same problem with if swift 3.2 project uses Atributika which compiled with swift 4.
Looks like this is compiler bug which I can't fix.
But you have two options:
1. port your project to swift 4
2. i just created `swift-3.2` branch, it is the same as master but for 3.2 swift

**Comment by MihauMihau** [comment]
Superb! Thanks so much, I'll check it later :)
