### ISSUE TITLE
Why onClick only when style contains any attributes for .highlighted?

### ISSUE THREAD

**Issue by rivera-ernesto** [psharanda/Atributika#120]
I think we shouldn't ask for `.highlighted` attributes fo this. Instead it could all be handled in the`onClick` configuration block.

**Comment by rivera-ernesto** [comment]
After actually using it, it now makes more sense 🤪

**Comment by psharanda** [comment]
Yeah API is not perfect. But haven't been able to find anything better.

**Comment by psharanda** [comment]
Actually, what if add modifier like this:
`let a = Style("a").userInteractionEnabled(true).foregroundColor(.blue)`
So there is no need to define something special to make text clickable

**Comment by psharanda** [comment]
I am also thinking about macOS, in addition to highlighted, text can have hover state

**Comment by rivera-ernesto** [comment]
Those sound like nice improvements!
Maybe `.tapEnabled()` (or click) is a better name. Same for hovering.

**Comment by psharanda** [comment]
userInteractionEnabled is more universal across platforms. Actually I just realized that there is no support for AttributedLabel on macOS :)

**Comment by psharanda** [comment]
This was reworked in V5. Closing this as obsolete
