### ISSUE TITLE
.foregroundColor with .highlighted attribute doesn't respect color property

### ISSUE THREAD

**Issue by divyeshmakwana96** [psharanda/Atributika#126]
When I use .normal `StyleType` it works as expected, but by setting .highlighted causes it to change to "all" foreground color

Below is my code for the **more** tag:
`
let more = Style("more").font(Font.UI.Assessment.highlightedText)
                .underlineStyle(.single)
                .foregroundColor(Color.UI.tintColor, .highlighted)
`

**Comment by psharanda** [comment]
Hi @divyeshmakwana96 ,
Could you provide more details and full code example?
