### ISSUE TITLE
Text with links disappears (Bug)

### ISSUE THREAD

**Issue by MRSorokinMaxim** [psharanda/Atributika#127]
- Only iOS 13 and higher
- Text without links does not disappears, but with links disappears
- Use custom transition animations between view controllers

![text_with_links_disappears](https://user-images.githubusercontent.com/25707911/91709328-43481380-eb8b-11ea-9814-70197dd957f4.gif)

**Comment by psharanda** [comment]
Hi @MRSorokinMaxim,
Could you provide sample project where this bug is reproducible?

**Comment by psharanda** [comment]
Might be fixed In V5
