### ISSUE TITLE
Support for Input

### ISSUE THREAD

**Issue by asifhabib** [psharanda/Atributika#131]
It is a great library to for attributed labels @mentions and #tags. I also need a library which should detect # and @ and then return search string after those characters, also should highlight the inserted hashtags and mentions.

**Comment by psharanda** [comment]
Hi,
Could you explain in more details your suggestion?

**Comment by asifhabib** [comment]
I need a textInput/UITextview which can detect # , @ or any special character and return string after that character. 

Like this library. 
https://github.com/JNDisrupter/JNMentionTextView
