### ISSUE TITLE
AttributedLabel height not set in SwiftUI List

### ISSUE THREAD

**Issue by dannyBuonocore** [psharanda/Atributika#132]
Maybe I'm doing something wrong, but I'm having issues setting the height of a multi-line `AttributedLabel` when it's in a SwiftUI `List` or `ScrollView`.

Please refer to this [minimal reproducible example](https://github.com/dannyBuonocore/Atributika-Test)

It works perfectly fine when I use a `UITextView` or a `UILabel` but I need to handle touches on html links.

**Comment by psharanda** [comment]
Hi,
Works for me if set `translatesAutoresizingMaskIntoConstraints` to `false`
```
struct HTMLViewAttributedLabel: UIViewRepresentable {
  let html: String
  
  func makeUIView(context: Context) -> AttributedLabel {
    let all = Style.font(.systemFont(ofSize: 16))
    let link = Style("a")
      .foregroundColor(.systemTeal, .normal)
      .foregroundColor(.systemTeal, .highlighted)
    
    let attributedText = html
      .style(tags: link)
      .styleLinks(link)
      .styleAll(all)
    
    let label = AttributedLabel()
    label.attributedText = attributedText
    label.numberOfLines = 0
    label.translatesAutoresizingMaskIntoConstraints = false
    return label
  }
  
  func updateUIView(_ uiView: AttributedLabel, context: Context) {
    
  }
}
```

**Comment by sonysm** [comment]
any update?

**Comment by kronaxthedebugfixer** [comment]
I defined a variable on swiftUI side @State var size:CGSize = .zero and I binded size to this view 
self.size = label.sizeThatFits(label.superview?.bounds.size ?? .zero)
and I can use size like this : 
.frame(width: size.width , height: size.height)

**Comment by psharanda** [comment]
Please check a SwiftUI [example](https://github.com/psharanda/Atributika/blob/038163ad8854dfdcb0d127e54a24566ae1522034/Demo/Sources/SwiftUIDemoViewController.swift#L11) in the demo project
