### ISSUE TITLE
Long Paragraph showing only one line

### ISSUE THREAD

**Issue by irchriscott** [psharanda/Atributika#135]
Hello,
Thank you or this awesome library, although, when when i display a long text in `UILabel`, it only show 1 centered line and cut out the other text
![InkedIMG_5057_LI](https://user-images.githubusercontent.com/32145966/97703370-8f4b0200-1ac1-11eb-8b77-4ec3ea04e5d9.jpg)

**Comment by sahibhussain** [comment]
set the numberOfLines to 0
