### ISSUE TITLE
Drop iOS 8 support

### ISSUE THREAD

**Issue by damirstuhec** [psharanda/Atributika#139]
Any chance we could drop support for iOS 8 to avoid this warning on Xcode 12+?
> The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99.

I'm using SPM. Thanks!

**Comment by mflknr** [comment]
Any news on this one? The warning is driving me crazy :D

**Comment by psharanda** [comment]
Resolved in 4.10.1
