### ISSUE TITLE
Got Xcode version error in Fastlane / circleCI

### ISSUE THREAD

**Issue by SyedHyderSaal** [psharanda/Atributika#141]
The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'Atributika' from project 'Atributika')
 
 All iOS apps submitted to the App Store must be built with the iOS 13 SDK or later, included in Xcode 11 or later. Further, starting April 26, 2021 iOS apps submitted to the App Store must be built with the iOS 14 SDK or later, included in Xcode 12 or later.
 
 I request you to change the Xcode version in Swift Package Manager
 
 Change below code:
 ```
platforms: [.macOS(.v10_10),
                                  .iOS(.v8),
```
to
```
platforms: [.macOS(.v10_10),
                                  .iOS(.v10),
```

**Comment by psharanda** [comment]
Resolved in 4.10.1
