### ISSUE TITLE
Voice Over jumps to first phone number after swiping to end

### ISSUE THREAD

**Issue by LittlePeculiar** [psharanda/Atributika#145]
I'm using the library to highlight text numbers and phone numbers and make them tappable. It work and looks great. But when Voice Over is turned on, the user can swipe to the end as usual and after reaching the bottom if they swipe again, it jumps back up to the first number so that it's reading just the number again and not able to tap it for function. Is there any way to disable this? Or a workaround? I'm using a simple Style() and I don't see a setting for this. Please help - thanks

**Comment by psharanda** [comment]
This should be fixed now
