### ISSUE TITLE
work with textview

### ISSUE THREAD

**Issue by dimabiserov** [psharanda/Atributika#146]
pls)

**Comment by psharanda** [comment]
Not sure this answers the question, but In v5 there are two views now - AttributedLabel and AttributedTextView, they are baked by UILabel and UITextView respectively

**Comment by dimabiserov** [comment]
> Not sure this answers the question, but In v5 there are two views now - AttributedLabel and AttributedTextView, they are baked by UILabel and UITextView respectively

big thx!
