### ISSUE TITLE
Character highlighting breaks if used \r and \n HTML tags together

### ISSUE THREAD

**Issue by vinayakparmar92** [psharanda/Atributika#15]
Highlighting is missing for few letters of the tagged link. Here is the example text(I am tagging a hashtag with a link)

> Worried about delivery? You must know these things!<br />\r\nLINK<br />\n <b><a style=\"text-decoration:none\" href=\"LINK"><font color=\"#2b5998\"><span>#</span></font><font color=\"#2b5998\">Childbirth</font></a></b>  <b><a style=\"text-decoration:none\" href=\"LINK"><font color=\"#2b5998\"><span>#</span></font><font color=\"#2b5998\">Expectingababy</font></a></b> 

If I remove all the \r tags from HTML then it works fine

**Comment by psharanda** [comment]
Hi, please provide the whole code snippet, or better pull request with failing test

**Comment by vinayakparmar92** [comment]
@psharanda [Here](https://github.com/psharanda/Atributika/pull/16) is the pull request. Also its the first time I am contributing to open source project. Please pardon me and give me feedback if any mistake was done. It will seriously help me

**Comment by psharanda** [comment]
@vinayakparmar92 There was a mistake in your test. Ranges between String and NSAttributedString must be converted using special methods. After a fix test is green. I tried to reproduce your issue with /r/n but everything looks fine for me. 
Please provide the whole code snippet here. That one where you see wrong highlight.

**Comment by vinayakparmar92** [comment]
I will post the code soon. Currently I have put a hack by replacing the string "\r\n" with "\r \n". Then it works totally fine.
