### ISSUE TITLE
Ignore tags from user input

### ISSUE THREAD

**Issue by LaCost765** [psharanda/Atributika#152]
Hello. I have a case when I apply style for user input text like this: "Hello mr \<b>\(userInput)\</b>!". It can be clearly seen, that I want make bold text from user input. But if user input contains < and something else after that sign, .style method detect this like tag too and \<b>\</b> breaks down. So, is it possible to ignore tags from user input in that case? TY in advance
P.S. Sorry for my terrible English :)

**Comment by psharanda** [comment]
Hi! You should escape the user input first e.g. replace `>` with `&gt;` etc
