### ISSUE TITLE
tag a has problem when set title tag a like url

### ISSUE THREAD

**Issue by sk-chanch** [psharanda/Atributika#153]
when string tag a is <a href=\"https://food.trueid.net/detail/WeX36y1rkg7J\">www.food.trueid.net</a> Atributika detect title not url in href

**Comment by sk-chanch** [comment]
i just remove function styleLinks it work!

**Comment by sk-chanch** [comment]
i'm create [pull request](https://github.com/sk-chanch/Atributika?organization=sk-chanch&organization=sk-chanch) to fixed this

**Comment by psharanda** [comment]
Please, check this [example](https://github.com/psharanda/Atributika/blob/038163ad8854dfdcb0d127e54a24566ae1522034/Demo/Sources/BrowserViewController.swift#L69) in the Demo project how to get url from a detected tag.
