### ISSUE TITLE
long urls highlight issue, please look

### ISSUE THREAD

**Issue by khashimov23** [psharanda/Atributika#155]
if there is a comma between the longer urls, then there is no highlight after comma

with comma:
<img width="230" alt="Screen Shot 2022-05-11 at 13 33 52" src="https://user-images.githubusercontent.com/60420279/167805906-dd42bda8-e92d-445a-b724-6a467bcaed01.png">

when the comma is deleted:
<img width="228" alt="Screen Shot 2022-05-11 at 13 34 01" src="https://user-images.githubusercontent.com/60420279/167826640-e00ec3e3-cad4-4f5a-8327-2ea4d19cb935.png">

**Comment by psharanda** [comment]
This is a bug in iOS data detectors, you can try to use a custom regex
