### ISSUE TITLE
Could you please make AttributesRangeInfo public getable?

### ISSUE THREAD

**Issue by cuzv** [psharanda/Atributika#169]
Thanks for your great work, using this library is really enjoyable, but now I have encountered a small problem.

The scenario is like this, I added an `NSAttributedString.Key` extension of my own, and I hope to be able to read it when assembling NSAttributedString:

```Swift
extension NSAttributedString.Key {
  public static let myOwnAttr = NSAttributedString.Key(rawValue: "myOwnAttr")
}

extension AttributedStringBuilder {
  func makeMyOwnVersionAttributedString() {
    // baseAttributes getable
    baseAttributes[.myOwnAttr]
    ...
    
    // can't get attributesRangeInfo
    let info = attributesRangeInfo.sorted {
      $0.level < $1.level
    }
  }
}
```

**Comment by cuzv** [comment]
Additional: If you are willing to accept such changes, I can submit a PR.

**Comment by psharanda** [comment]
Yeah, makes sense to open it. Feel free to create a PR 👍

**Comment by cuzv** [comment]
Since this feature has been merged, I am going to close this issue.
