### ISSUE TITLE
Unicode characters removed in 3.1.4 version?

### ISSUE THREAD

**Issue by vinayakparmar92** [psharanda/Atributika#17]
@psharanda If I use the style methods to highlight then Unicode is replaced with an empty string. Basically, I want to give support for Emojis. Is there not support for Unicode chars or I am missing out something?

**Comment by psharanda** [comment]
Emojis were fixed in v4. For swift 3.2 support check `swift-3.2` branch

**Comment by vinayakparmar92** [comment]
Got it!. Will try using that. Thanks for the quick response 👍
