### ISSUE TITLE
Failed with Bold/Italic nested tags

### ISSUE THREAD

**Issue by tiendnuit** [psharanda/Atributika#18]
It work wrong with Bold/Italic nested tags, example : 

`<br><u><i><b>Italicunderline</b></i></u>`

. How can I show this html?

**Comment by psharanda** [comment]
Atributika is not supposed to work exactly like web browser. It uses HTML-like tags to select ranges of string and style them. 
This is how you can have bold italic: 
```swift
let font = UIFont(name: "HelveticaNeue-BoldItalic", size: 12)!
let uib = Style("uib").font(font).underlineStyle(.styleSingle)
let str = "<br><uib>Italicunderline</uib>".style(tags: uib).attributedString
```
