### ISSUE TITLE
Not adding foreground colours

### ISSUE THREAD

**Issue by wratke** [psharanda/Atributika#23]
This is a really nice framework, but I can't seem to get the foreground colour working. I've dropped the first Hello World example directly into my project, but it all shows up black. I'm not sure if I'm missing something.

**Comment by wratke** [comment]
Never mind, I just noticed that I had set the colour somewhere else in my code. Thanks again for the framework, it saves a lot of time dealing with attributed strings.

**Comment by psharanda** [comment]
Hey. Thanks for good words. You are welcome!
