### ISSUE TITLE
Full HTML Support?

### ISSUE THREAD

**Issue by n1tesh** [psharanda/Atributika#3]
Is it possible to have full HTML support in this ? I have a label in which I had set attributedText with NSAttributedString which consorting all data with html tags.I need Hash tag detection implementation in that.

**Comment by psharanda** [comment]
Atributika requires you to define explicitly all the tags you want to style. You have two ways for HTML support
1. Not full, but working way. You need to define styles by yourself for most common HTML tags like **b**, **i**, **strong** etc. 
2. Full support, but slow way. You can create `NSAttributedString` using `NSHTMLTextDocumentType`. Regular NSAttributedString conforms `Atributika` protocol and supports hashtags styling too.

**Comment by n1tesh** [comment]
@psharanda I tried the second way but it didn't worked for me. Can you try and share if it works with you?

**Comment by psharanda** [comment]
Using second way:
```
    let str = "<b>Hello</b> #World"
    let data = str.data(using: .utf8)
    let options: [String: Any] = [NSDocumentTypeDocumentAttribute: NSHTMLTextDocumentType,
                   NSCharacterEncodingDocumentAttribute: String.Encoding.utf8.rawValue]
    
    let htmlAttrString = try! NSAttributedString(data: data!, options: options, documentAttributes: nil)
    let result = htmlAttrString.styleHashtags(Style.foregroundColor(.blue)).attributedString
```
