### ISSUE TITLE
Xcode 9.3.1 - Undefined symbols - Only when archiving.

### ISSUE THREAD

**Issue by Andre-FS** [psharanda/Atributika#32]
Similarly to https://github.com/psharanda/Atributika/issues/27, I'm having compilation errors when archiving with Xcode Version 9.3.1 (9E501).

```
Undefined symbols for architecture arm64:
  "protocol witness table for __C.NSAttributedStringKey : Swift.Equatable in Foundation", referenced from:
      function signature specialization <Arg[0] = Owned To Guaranteed, Arg[1] = Dead> of generic specialization <__C.NSAttributedStringKey, Any> of static (extension in Swift):Swift._NativeDictionaryBuffer< where A: Swift.Hashable>.fromArray([(A, B)]) -> Swift._NativeDictionaryBuffer<A, B> in MutableAttributedString+Utils.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Instead of mentioning Hashable, like in https://github.com/psharanda/Atributika/issues/27, my error mentions Equatable.

I was able to fix this by adding:
```
#if swift(>=4.1)
extension NSAttributedStringKey: Equatable { }
#endif
```

Would you consider adding this workaround while we wait for the inner Swift bug to be fixed?

Thanks!

**Comment by psharanda** [comment]
Uh this is strange, because Hashable is already Equatable

**Comment by Andre-FS** [comment]
I know. It really is very strange. 

Adding that extension on my project made Xcode say that (surprise) `NSAttributedStringKey` is already `Equatable`. However, adding it to the Atributika project fixed the problem.

There's definitely something buggy happening here, and it's probably on Swift's side. I just don't know what it is..

**Comment by psharanda** [comment]
Sorry, busy week. Feel free to post PR.

**Comment by psharanda** [comment]
alright, i put fix

**Comment by zaptrem** [comment]
@psharanda How did you fix this? I’m dealing with it in another library.
