### ISSUE TITLE
Images are not loaded

### ISSUE THREAD

**Issue by lendkazazi** [psharanda/Atributika#33]
The images in html text do not show at all. How is it possible to implement images while using atributika.

Thanks

**Comment by psharanda** [comment]
You can post process you result string using detections info provided by Atributika. Here is an example how to do this

````swift
func stringWithImage() -> NSAttributedString {
    
    let str = "Running with <img id=\"scissors\"></img>!".style(tags: [])
    
    let mutableAttrStr = NSMutableAttributedString(attributedString: str.attributedString)
    
    var locationShift = 0
    for detection in str.detections {
        switch detection.type {
        case .tag(let tag):
            if let imageId =  tag.attributes["id"] {
                let textAttachment = NSTextAttachment()
                textAttachment.image = UIImage(named: imageId)
                let imageAttrStr = NSAttributedString(attachment: textAttachment)
                let nsrange = NSRange.init(detection.range, in: mutableAttrStr.string)
                mutableAttrStr.insert(imageAttrStr, at: nsrange.location + locationShift)
                locationShift += 1
            }
        default:
            break
        }
    }

    return mutableAttrStr
}
````

**Comment by lendkazazi** [comment]
This still doesn't do show any images :(

**Comment by psharanda** [comment]
this code assumes that "id" is the name of image in local assets. if you want to load images from remote site this code needs to be reworked. basically you need to fetch images from server, and then update your attributed strings as soon as they are loaded

**Comment by lendkazazi** [comment]
the thing is that the moment i add a style, the tag "img" gets removed from the string, and doesn't go in the for loop you created.

**Comment by psharanda** [comment]
all `style*` methods return `AttributedText` not `NSAttributedString`. `AttributedText` contains all the info about detections and can be converted into `NSAttributedString`

**Comment by psharanda** [comment]
you can check demo app in repo, i put this example with scissors in latest commit

**Comment by lendkazazi** [comment]
i understand what you are trying to say, but i have to either show the image or add the styling, i cannot add image and style to the same textview.

**Comment by lendkazazi** [comment]
the moment i add styling there is no img

**Comment by lendkazazi** [comment]
`    func stringWithImage(text:String) -> NSAttributedString {
        
        let links = Style.foregroundColor(.blue)
        let b = Style("strong").font(UIFont.init(name: "RobotoCondensed-Bold", size: 15)!)
        let u = Style("u").underlineStyle(.styleSingle)
        let all = Style.font((UIFont.init(name: "RobotoCondensed-Regular", size: 15)!)).foregroundColor(.gray)
        
        let str = text.style(tags: [b,u]).styleAll(all).attributedString
        
        let mutableAttrStr = NSMutableAttributedString(attributedString: str)
        
        var locationShift = 0
        for detection in str.detections {
            switch detection.type {
            case .tag(let tag):
                
                if let imgSrc =  tag.attributes["src"] {
                    
                    let imageView = UIImageView()
                    imageView.af_setImage(withURL: URL.init(string:imgSrc)!, placeholderImage: #imageLiteral(resourceName: "ia_placeholder"))
                    
                    let textAttachment = NSTextAttachment()
                    textAttachment.image = imageView.image
                    let imageAttrStr = NSAttributedString(attachment: textAttachment)
                    let nsrange = NSRange.init(detection.range, in: mutableAttrStr.string)
                    mutableAttrStr.insert(imageAttrStr, at: nsrange.location + locationShift)
                    locationShift += 1
                }
            default:
                break
            }
        }
        
        return mutableAttrStr
    }`

**Comment by lendkazazi** [comment]
`for detection in str.detections {
        switch detection.type {
        case .tag(let tag):
            
            if let imgSrc =  tag.attributes["src"] {
                
                let imageView = UIImageView()
                imageView.af_setImage(withURL: URL.init(string:imgSrc)!, placeholderImage: #imageLiteral(resourceName: "ia_placeholder"))
                
                let textAttachment = NSTextAttachment()
                textAttachment.image = imageView.image
                let imageAttrStr = NSAttributedString(attachment: textAttachment)
                let nsrange = NSRange.init(detection.range, in: mutableAttrStr.string)
                mutableAttrStr.insert(imageAttrStr, at: nsrange.location + locationShift)
                locationShift += 1
            }
        default:
            break
        }
    }`

This doesn't get called at all

**Comment by lendkazazi** [comment]
i found the issue, tags that don't have a closure with their name don't get recognized as tags(ex:<img class ------------/>). They must contain <img></img> to get recognized as a tag.

Thanks :)
