### ISSUE TITLE
Style.swift Crash

### ISSUE THREAD

**Issue by Mahan3340** [psharanda/Atributika#34]
Hi , Style.Swift line 84 and AttributedText.swift line 99 crash , swift 4.1 , Xcode 9 latest version , ios 11 , 
just copy pasted your "link" and "all" code and crashesh without doing anything else
here's the code : `let tweetLabel = AttributedLabel()

        let all = Style.font(.systemFont(ofSize: 20))
        let link = Style
            .foregroundColor(.blue, .normal)

        tweetLabel.attributedText = "@Hey"
            .styleHashtags(link)
            .styleMentions(link)
            .styleLinks(link)
            .styleAll(all)`
adding `.foregroundColor(.brown, .highlighted)` to link will result. style.swift to crash o.w AttributeText.swift does

**Comment by psharanda** [comment]
hi. do you mean compiler crash or app crash?

**Comment by Mahan3340** [comment]
It' builed and run successfully , app crashes as soon as it reaches to these lines

**Comment by psharanda** [comment]
can you provide crash call stack?

**Comment by Mahan3340** [comment]
[log.zip](https://github.com/psharanda/Atributika/files/2096958/log.zip)
here's crash log for both case

**Comment by Mahan3340** [comment]
if there was printed anything I would have told u , nothing is printed when crash happenes , theres' and that moment on that there is just a red line in which the crash has happened and Thread num and .. just like other crashesh , but nothing is printed or nil , told u the lines crash happens at

**Comment by psharanda** [comment]
Alright, something strange is going there. There is nothing to crash at these lines. Likely something with your project. Try to create new test project and check if it works for you.

**Comment by Mahan3340** [comment]
<img width="1097" alt="s1" src="https://user-images.githubusercontent.com/21075867/41347215-2a4ad156-6f1e-11e8-9419-b9ce558fd94f.png">
<img width="1095" alt="s2" src="https://user-images.githubusercontent.com/21075867/41347216-2a898da6-6f1e-11e8-8781-b248d1cafea6.png">

screenshots , I'll try on a new test project and let you know

**Comment by psharanda** [comment]
maybe this can help you to understand what happens https://forums.developer.apple.com/thread/65953

**Comment by Mahan3340** [comment]
actually I tested it on a different project and its working fine , gotta  debug a bit more to figure it out , I'll close this issue for now and let you know if I found anything useful , thank you 😊
