### ISSUE TITLE
Give me example 

### ISSUE THREAD

**Issue by akirasakata** [psharanda/Atributika#35]
Hi,

I'ld like to use this great module.
Please give me a example working in TableViewCell.
 I tried this, but it can't work correctly. it is not tappable.

Thanks.

**Comment by psharanda** [comment]
Hi. Please take a look at `AttributedLabelDemoViewController.swift`

**Comment by akirasakata** [comment]
Thank you.
I apologize for lack of confirmation.

I checked my code again.
In my case,  I want to use addSubview() method to UIlabel on TableViewCell.
Below is short example.
```
let cell = tableView.dequeueReusableCell(withIdentifier: "...", for:indexPath)
let attributeLabel = AttributedLabel()
attributeLabel.attributedText = ...
attributeLabel.onClick = ...
//exampleUILabel is UILabel arranged on TableViewCell by storyboard
cell.exampleUILabel.addsubView(attributeLabel)
```
It show attributeLabel correctly, but  Onclick() don't work.

**Comment by psharanda** [comment]
guess you need to set `isUserInteractionEnabled` to `true` for your UILabel

**Comment by akirasakata** [comment]
Thanks a lot.
I resolved my problem.
It is not issue of this module. I'm sorry I've wasted your time.
