### ISSUE TITLE
Text is removed after "&" character when using style

### ISSUE THREAD

**Issue by zcsipler** [psharanda/Atributika#36]
Hi,

I have a text which might include "&" character, for example "Travel & Talk". I would like to format this text and show all the formatted text as an attributed string, but only "Travel" is shown in the result attributed string, rest of the string is removed. 

I guess the reason is this line in the String+Detection.swift file:

```
if let textString = scanner.scanUpToCharacters(from: CharacterSet(charactersIn: "<&")) {
...
```

**Example Code:**

```
let aStyle = Style("a")
            .underlineStyle(.styleSingle)

let html = "Travel & Talk"

let attributedText = html
      .style(tags: aStyle)

print(attributedText)
```

**Result:**

`AttributedText(string: "Travel ", detections: [], baseStyle: Atributika.Style(name: "", typedAttributes: [:]))`

Is there any way that we can also include "&" character in the attributed string?

**Comment by psharanda** [comment]
Hi, you need to escape special HTML characters before using `style(tags:)`
So correct string must be `let html = "Travel &amp; Talk"`
Read more here https://www.w3schools.com/html/html_entities.asp
Atributika supports just these for the moment https://github.com/psharanda/Atributika/blob/master/Sources/String%2BDetection.swift#L87

**Comment by psharanda** [comment]
But actually it can be not so strict 🤔

**Comment by zcsipler** [comment]
Thanks, I will find a way then to replace special characters like this in the text!
