### ISSUE TITLE
I cannot add strikethrough attribute.

### ISSUE THREAD

**Issue by denniskeithgaso** [psharanda/Atributika#37]
Here is my sample code. The `<code>` tag displays well in red color. But the `<strike>` tag does not show a strikethrough. What seems to be wrong with my code?
```
let all = Style.font(.systemFont(ofSize: 20))
let strike = Style("strike").strikethroughStyle(.styleSingle).strikethroughColor(.black)
let code = Style("code").foregroundColor(.red)

label5.attributedText = "<code>my code</code> <strike>test</strike> testing"
            .style(tags: [strike,code])
            .styleAll(all)
```

**Comment by psharanda** [comment]
I tested and it works fine for me. Maybe you have a problem like here https://stackoverflow.com/questions/43074652/ios-10-3-nsstrikethroughstyleattributename-is-not-rendered-if-applied-to-a-sub

**Comment by denniskeithgaso** [comment]
It's working well now. Thank you.
I'm closing this issue.
