### ISSUE TITLE
BR was not replaced

### ISSUE THREAD

**Issue by prsolucoes** [psharanda/Atributika#38]
Hi,

My <br> tags was not replaced:

![image](https://user-images.githubusercontent.com/395096/42964176-a1fdd814-8b6c-11e8-935d-556c4bfc3582.png)

My code:

```
 let paragraph = NSMutableParagraphStyle()
paragraph.lineBreakMode = .byTruncatingTail
            
let all = Style.font(.systemFont(ofSize: 14)).foregroundColor(.white).paragraphStyle(paragraph)
lbSynopsis.attributedText = product.synopsis.styleAll(all).attributedString
```

Can anyone help me?

**Comment by psharanda** [comment]
Hello,
Just `style(tags:)` method parses string as HTML and returns modified version.` styleAll()` just applies attributes to the whole string

**Comment by prsolucoes** [comment]
But i need specify every html tag there?

**Comment by psharanda** [comment]
just those you want to style. so if you want to remove br, just pass empty array
