### ISSUE TITLE
NSTextAttachment does not show image. I'm using attachment() method.

### ISSUE THREAD

**Issue by denniskeithgaso** [psharanda/Atributika#39]
I need help. I cannot display image between text using NSTextAttachment.
Here is my code:

```
let image1Attachment = NSTextAttachment()
image1Attachment.image = UIImage(named: "profile")

    let all = Style.font(UIFont.systemFont(ofSize: 17)).foregroundColor(.black)
    let atch = Style("attachment").attachment(image1Attachment)
    
    attributed.attributedText = "Hello this is my attachment <attachment></attachment> A simple image"
        .style(tags: [all, atch])
        .styleAll(all)
```

**Comment by NervousTweek** [comment]
I think this function is not implemented yet. For now, if you want to add attachment as well as click detection to AttributedLabel, you can follow the `stringWithImage()` snippet example to make a attributedString object, style it and set it to an AttributedLabel. Here is the code:
`
    let rawString = "Here is an image <img id=\"scissors\"></img>"
    
    let label = AttributedLabel()
    // then setup the label and add to view
    // ... label setup code
    
    let str = rawString.style(tags: [])
    // make a NSMutableAttributedString with the raw string
    let mutableAttrStr = NSMutableAttributedString(attributedString: str.attributedString)
    
    // locate tags and insert attachments
    var locationShift = 0
    for detection in str.detections {
        switch detection.type {
        case .tag(let tag):
            if let imageId =  tag.attributes["id"] {
                let textAttachment = NSTextAttachment()
                textAttachment.image = UIImage(named: imageId)
                let imageAttrStr = NSAttributedString(attachment: textAttachment)
                let nsrange = NSRange.init(detection.range, in: mutableAttrStr.string)
                mutableAttrStr.insert(imageAttrStr, at: nsrange.location + locationShift)
                locationShift += 1
            }
        default:
            break
        }
    }
    
    // set other styles
    let all = Style.font(.systemFont(ofSize: 20))
    let link = Style
        .foregroundColor(.blue, .normal)
        .foregroundColor(.brown, .highlighted)
    
    // set the final styled AttributedText to label
    label.attributedText = mutableAttrStr
        .styleHashtags(link)
        .styleMentions(link)
        .styleLinks(link)
        .styleAll(all)
`
It works fine for me.

**Comment by denniskeithgaso** [comment]
Thank you! It worked for me.
