### ISSUE TITLE
Installation via CocoaPod

### ISSUE THREAD

**Issue by tevghenii** [psharanda/Atributika#4]
Hello,

I would like to try the library in my project.
Unfortunately CocoaPods shows an error on installation process:
```
$ pod install
Analyzing dependencies
[!] Unable to find a specification for `Atributika`
```

My Podfile:

```
target 'Project'
use_frameworks!
pod 'Atributika'
```

Is any way to install the Atributika via CocoaPods? 

Thanks

**Comment by psharanda** [comment]
Hello,
It works for me. Likely there is something wrong with your setup. Try to check this thread https://github.com/CocoaPods/CocoaPods/issues/3877

**Comment by tevghenii** [comment]
Got it.
`pod repo update` resolved my issue.
