### ISSUE TITLE
Styling broken as soon as '&' is found with link display name

### ISSUE THREAD

**Issue by jhaliya** [psharanda/Atributika#40]
Hello Pavel Sharanda,
I'm pleased with this library and intended to use with one of my projects, I would say it's very robust and great in term of performance but there is an issue when a **&** comes within **<a>** tag.

Below is the HTML for your reference.

`<p><a data-mention=\\\"0F9o0000000PBpMCAW\\\" href=\\\"https://www.google.com\\\”>@Physic & Chemistry</a>\\U00a0<a data-mention=\\\"0F9o000000094o4CAA\\\" href=\\\"https://www.google.com\\\”>@College Success</a>\\U00a0sorry for the short notice, but a great seminar to share with all of you .</p>
`
I received only **Physic**  as the result nsattributedstring.

A quick reply would be appreciated.

Thanks.

**Comment by psharanda** [comment]
Yeah it is a known issue. For the moment just use &amp;
