### ISSUE TITLE
href support?

### ISSUE THREAD

**Issue by Gerrel** [psharanda/Atributika#43]
I've got the following text:

`<p>Je ontvangt je factuur elke maand per post. Daarvoor betaal je € 2,54 per maand. <br />Wil je deze kosten besparen? Meld je dan aan voor een gratis digitale factuur. <a href=\"https://www.google.nl/my/instellingen#betaalgegevens\">Pas je instellingen aan ></a></p>
`

In the code I've added:
```
let a = Style("a").foregroundColor(.customRed()).underlineStyle(.styleSingle)
        let all = Style.font(.defaultMediumFont(withSize: 12.0)).foregroundColor(.invoiceRemarksGray()).kern(-0.3)

self.remarksDescriptionLabel.attributedText = decoded.style(tags: a)
                                                        .styleAll(all)
                                                        .stylePhoneNumbers(Style.foregroundColor(.customRed()))
                                                        .styleLinks(Style.foregroundColor(.customRed()))

self.remarksDescriptionLabel.onClick = { label, detection in
            switch detection.type {
...
}
```
But I never get a onClick event!?

**Comment by denniskeithgaso** [comment]
You need to set the onClick.
For your code, you can add:
`self.remarksDescriptionLabel.onClick = { label, detection in
            switch detection.type {
            case .tag(let tag):
                let t = tag.attributes
                if let href = t["href"] {
                    if let url = URL(string: href) {
                        UIApplication.shared.open(url, options: [:], completionHandler: nil)
                    }
                }
            default:
                break
            }
        }`

**Comment by Gerrel** [comment]
It works when I'm appending '\n' to the string.
It seems that the detection area is not correct when the link is at the end of the string.
(the view does not clip and bounds are correct)

**Comment by psharanda** [comment]
Hi,
To make something clickable you need to provide style with .highlighted type. It is the way to mark parts of strings you want to make clickable.
```
let link = Style
                .foregroundColor(.blue, .normal)
                .foregroundColor(.brown, .highlighted)
```

**Comment by Gerrel** [comment]
Yes I’ve got things working now with \n.
Will provide a small test project for this issue to reproduce and open a new issue for this.
