### ISSUE TITLE
Honour basic HTML style formatting

### ISSUE THREAD

**Issue by jozko-pucik** [psharanda/Atributika#44]
Hi,
would it be possible to honour basic HTML styling attributes? We have a basic HTML text like this:
`Monday - Friday: <font color="#6cc299"> 8:00 - 19:00</font>` 
and the tags get transformed / stripped off, but the color attribute is lost. Or is there a way how to achieve this with a TagTransformer anyhow? Please note that the color attribute varies in the HTML text, so applying one style to FONT tag is not the way to go.
Thanks

**Comment by psharanda** [comment]
Hi, 
Thanks for interesting use case. Please check latest version. I added new param to style(tags:) method which allows to precisely configure style depending on tag and its attributes.

**Comment by psharanda** [comment]
https://github.com/psharanda/Atributika/blob/f9bc6ed089e1f4eafe2e9995d3f873e06baca0e5/Tests/AtributikaTests/AtributikaTests.swift#L486

**Comment by psharanda** [comment]
yeah, makes sense. just added support for single quote. thanks for feedback.
