### ISSUE TITLE
href support

### ISSUE THREAD

**Issue by abhikpo** [psharanda/Atributika#45]
Hi,
href are not working. The following code snippet is an example. Can you look into it where we did the mistake?
Also, unable to click **Facebook** link. If I am displaying as **Facebook.com**, it is clickable.
        
        let href = "<a href=\"https://www.google.com/\">Google.com</a>  href  <a href=\"https://www.facebook.com/\">Facebook</a>"
        
        let a = Style("a").foregroundColor(.green).underlineStyle(.styleSingle)
        let all = Style.font(.systemFont(ofSize: 20.0)).foregroundColor(.gray)
        let link = Style.foregroundColor(.green, .normal).foregroundColor(.red, .highlighted)
        
        hrefLink.attributedText = href.style(tags: a)
            .styleAll(all)
            .styleLinks(link)
        
        hrefLink.numberOfLines = 0
        
        hrefLink.onClick = { label, detection in
            switch detection.type {
            case .tag(let tag):
                let t = tag.attributes
                if let href = t["href"] {
                    if let url = URL(string: href) {
                        if #available(iOS 10.0, *) {
                            UIApplication.shared.open(url, options: [:]
                                , completionHandler: nil)
                        } else {
                            // Fallback on earlier versions
                        }
                    }
                }
            case .link(let url):
                UIApplication.shared.open(url, options: [:]
                    , completionHandler: nil)
            default:
                break
            }
        }

**Comment by psharanda** [comment]
`styleLinks` - detects and styles regular links in text (not placed in tags). So you need just add `.higlighted` support  to `'a'` style

  ```
  let href = "<a href=\"https://www.google.com/\">Google.com</a>  href  <a href=\"https://www.facebook.com/\">Facebook</a>"
    
    let all = Style.font(.systemFont(ofSize: 20.0)).foregroundColor(.gray)
    let a = Style("a").foregroundColor(.green, .normal).foregroundColor(.red, .highlighted)
    
    hrefLink.attributedText = href.style(tags: a)
        .styleAll(all)
```
