### ISSUE TITLE
No detection on tags. 

### ISSUE THREAD

**Issue by asifSdSol** [psharanda/Atributika#46]

**Comment by asifSdSol** [comment]
I have to add some text to bold. Working fine but not taking detection.

**Comment by psharanda** [comment]
check this example https://github.com/psharanda/Atributika#attributedlabel
you need to set at least one style attribute as `.highlighted`

**Comment by asifSdSol** [comment]
I did not mean Hashtags, I mean tag. I want to show one word bold and want to take detection on that word. I used tag <b> but it is not taking detection.

**Comment by psharanda** [comment]
It doesn't matter which kind of detections you have - tags, hashtags or links. Just set at least one style attribute as `.highlighted`
```
let b = Style("b")
    .foregroundColor(.blue, .normal)
    .foregroundColor(.brown, .highlighted) // <-- detections with this style will be clickable now
```

**Comment by asifSdSol** [comment]
Thanks You Pavel Sharanda. Love and respect from Pakistan.
