### ISSUE TITLE
Feature to detect <a href = "">

### ISSUE THREAD

**Issue by Ankish** [psharanda/Atributika#47]
It works great for all tags of HTML. But using 'a' tag a href = "url" is a major scope. If we could get a support for that, it will be great. Thanks

**Comment by psharanda** [comment]
i don't understand what is the exact problem?

**Comment by Ankish** [comment]
"<span>Some text<span>" or "<b> text <b>""- we could style this using the library
If I need to convert an HTML string "<a href = "url"> </a>"  with a link to an attributedString, its not possible with current implementation. To support a href HTML tags to convert the parser needs to detect the href string with url inside and handle the clicks.
Will it be possible to support that ?

**Comment by Ankish** [comment]
*edited . Git editor is converting the html tags and its not readable as an issue. I have edited. Kindly check the issue

**Comment by psharanda** [comment]
https://github.com/psharanda/Atributika/issues/43
