### ISSUE TITLE
Issue with & characters

### ISSUE THREAD

**Issue by Placeable** [psharanda/Atributika#5]
Text with **&** characters will strip all styled text following said character.  See the following example:
```
let msg = "Hello & <b>Welcome!</b>"
let b = Style("b").font(Font(name: "Verdana-Bold", size: 22)!)
let strCopy = msg.style(tags: [b]).styleAll(Style.font(Font(name: "Verdana", size: 22)!))
txtView.attributedText = strCopy.attributedString
```

Displayed text in txtView will simply be: "Hello "

I understand Atributika supports HTML characters so perhaps that is what is causing it? Is it possible to work around that or disable it somehow?

**Comment by psharanda** [comment]
You need to escape some symbols exactly like in HTML. Use &amp; instead of &.

**Comment by Placeable** [comment]
Yeah just figured that, e.g:
`msg = msg.replacingOccurrences(of: "&", with: "&amp;")`

Works like a charm, thanks!
