### ISSUE TITLE
Swift 4.2

### ISSUE THREAD

**Issue by rafsouzap** [psharanda/Atributika#51]
Are there plans for Swift 4.2 support?

<img width="369" alt="screen shot 2018-09-19 at 14 49 57" src="https://user-images.githubusercontent.com/2496520/45771417-6c2fa200-bc1b-11e8-8b40-298f246244e1.png">

**Comment by psharanda** [comment]
You can use swift 4 libs in swift 4.2 projects. Some popular libs like Alamofire are still using Swift 3. Just don't touch Atributika project and it will be fine.

**Comment by psharanda** [comment]
Probably you made some changes to Atributika changes by migration tool. Just revert them.

**Comment by psharanda** [comment]
Alright, looks like all the other libs are still adding support for swift 4.2 using `#ifdef`s. Maybe there are some important cases to do this. I added support for swift 4.2 in recent release.
