### ISSUE TITLE
<ul> and <ol> support ?

### ISSUE THREAD

**Issue by jazz-mobility** [psharanda/Atributika#53]
Hi,

First of all, I am really impressed by this project and appreciate the efforts you put in.
Just want to know, if it possible to support bullet points and numbered list?

I am happy to create a PR if you guide me on how to's and basic project structure.

**Comment by psharanda** [comment]
Hi, thanks for good words
There is no default support for lists. But Atributika has such thing as TagTransformer. Using it you can replace opening and closing tags with any value.
Check examples here
https://github.com/psharanda/Atributika/blob/master/Demo/Snippet.swift#L126
and here 
https://github.com/psharanda/Atributika/blob/master/Tests/AtributikaTests/AtributikaTests.swift#L358

**Comment by jazz-mobility** [comment]
Hi Pavel,

Thanks for the quick reply. I'll give it a try.
