### ISSUE TITLE
Custom truncation token

### ISSUE THREAD

**Issue by ily9000** [psharanda/Atributika#55]
Great library, it's very useful to style links and tags. 
It would be nice to have custom truncation tokens similar to TTAttributedLabel to replace the default ellipses in UILabel so I can stop using TTAttributedLabel in certain cases.

It'd be similar to 
https://github.com/TTTAttributedLabel/TTTAttributedLabel/blob/b0f1f93d5d4368a7aaf52e848013a1b40b00dc3c/README.md

**Comment by psharanda** [comment]
For the moment AttributedLabel uses UILabel for rendering. UILabel doesn't support custom truncation tokens
