### ISSUE TITLE
A-Tags

### ISSUE THREAD

**Issue by 343max** [psharanda/Atributika#57]
Hey! I'm trying to figure out how to convert `<a>` Tags into clickable links. I tried `.style(links:)` but that wouldn't work. Do I miss something very obvious?

**Comment by 343max** [comment]
I found a workaround, but it's very ugly:
```
    attributedStringValue = html
      .style(tags: [displayName, at, aStyle], tuner: { style, tag in
        switch tag.name.lowercased() {
        case "a":
          if style.typedAttributes[.normal]?[.link] as? String == hrefLinkReplacement, let href = tag.attributes["href"] {
            return style.link(href)
          } else {
            return style
          }
        default:
          return style
        }
      })
      .styleAll(allStyle).attributedString
```

**Comment by psharanda** [comment]
Just make “a” tags clickable. In click handler, check if tag is “a”,  extract href url and perform your logic there

**Comment by 343max** [comment]
How do I make something clickable? The only thing I could find is the `AttributedLabel`, which is a `UIView` subclass and thereby only available on iOS.

**Comment by psharanda** [comment]
Ah, I see. That is why I created AttributedLabel. Link attribute is limited, you can’t style it properly if using in standard textView. But I can consider porting it to macOS

**Comment by 343max** [comment]
It works with the workaround I posted, but this is not very elegant. There is no easier way?

**Comment by psharanda** [comment]
It’s ok, I just don’t understand why you compare with some hreflinkreplacement

**Comment by 343max** [comment]
I do this because I couldn't find an easier way to turn a-tags into links. What is the official way?

**Comment by psharanda** [comment]
Your way using tuner is fine. I don’t understand why you need that particular comparison with hrefLinkReplacement

**Comment by 343max** [comment]
So when I just replace links like this:
```
let aStyle = Style("a")
      .foregroundColor(NSColor.linkColor, .normal)
      .link("https://some.url")
```
I have to provide an URL, I couldn't find a way to just tell it "use the href value". So I'm setting placeholder links on these and am replacing them afterwards. I do the comparison so the original intended way still works, in case I need it later.

**Comment by psharanda** [comment]
Ok then it is actually not bad workaround
