### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by NiharDodiya** [psharanda/Atributika#59]
<  href="https://www.w3schools.com">This is link</a> I have set this link to 'AttributedLabel' but it not working. when  i click on "This is link" it went to case .tag(let tag): and get tag "Tag(name: "a", attributes: [:])". why i am not getting attributes? i have remove <a?> in href for here just to display proper link in issue

**Comment by psharanda** [comment]
Please show your code sample and wrap it with code tokens(```), so github will display it correctly
