### ISSUE TITLE
Get the frame of a certain range of text so that I can add a custom button or view

### ISSUE THREAD

**Issue by denniskeithgaso** [psharanda/Atributika#61]
Hi!
Thanks for this awesome library! One of the most powerful out there.
I have a question:
Is it possible to get the frame of a specific text using NSRange?
I want to get the frame so that I can add a subview in that coordinate, like a custom button or a view.

For example the text `this is a text and this is a button`
How can I get the frame of the `button` word so that I can add a subview in that coordinate that will cover that word.

Any help is greatly appreciated.
Thanks a lot!

**Comment by psharanda** [comment]
You can check AttributedLabel source code. It creates buttons for links

**Comment by denniskeithgaso** [comment]
It worked! Thanks!
