### ISSUE TITLE
Background color and font color

### ISSUE THREAD

**Issue by sergstav** [psharanda/Atributika#62]
Hi, is this possible to get attributes from tag and set it to Style object.
For example I get this 
<span style=\"background-color:rgb(192,80,77);\">красный<\/span><\/p><p><span style=\"color:rgb(192,80,77);\">просто красный шрифт<\/span><\/p>
How can I do text просто красный шрифт will be red, and span bg is red?
I mean, this attributes can be any, yellow, red, it comes from server.

**Comment by psharanda** [comment]
Hi, you can use tuner param like here
https://github.com/psharanda/Atributika/blob/master/Tests/AtributikaTests/AtributikaTests.swift#L540
