### ISSUE TITLE
How to detect click action on normal string?

### ISSUE THREAD

**Issue by terasupernova** [psharanda/Atributika#63]
Hi, is there a way to detect a click on the normal string rather than the tag?

For example when click on the "BROOKS WOMEN'S RICOCHET Products shown:" and "abcd efg hj" in the screen shot. The onClick function will cater for this? 

<img width="1083" alt="screen shot 2018-11-25 at 9 41 37 pm" src="https://user-images.githubusercontent.com/8252838/48979805-efc5ad80-f0fa-11e8-944c-31e259538f31.png">

Thank you.

**Comment by psharanda** [comment]
Hi, you can just wrap "abcd efg hj" into tag, but use base style for it (not the blue one).

**Comment by terasupernova** [comment]
Hi, @psharanda. Can you provide a sample / demo on how to do this? I not sure how to do this. Thanks again.

**Comment by psharanda** [comment]
```
let all = Style.font(.systemFont(ofSize: 20))
            let link = Style("a")
                .foregroundColor(.blue, .normal)
                .foregroundColor(.brown, .highlighted)
            
            let hiddenLink = Style("ah", [.normal : all.attributes, .highlighted : all.attributes])

            tweetLabel.attributedText = "BROOKS WOMEN'S RICOCHET\nProducts shown: <a>Product</a>\n<ah>abcd efg hj</ah>"
                .style(tags: link, hiddenLink)
                .styleHashtags(link)
                .styleMentions(link)
                .styleLinks(link)
                .styleAll(all)
```
