### ISSUE TITLE
Paragraph style

### ISSUE THREAD

**Issue by rafsouzap** [psharanda/Atributika#67]
Hello

I have a HTML text similar to this example:
`<p>Sample Text 1</p><p>Sample Text 2</p>`

And I need to display it this way:
Sample Text 1
Sample Text 2

My question is how to set the <p> tag to make the line break correctly.

**Comment by psharanda** [comment]
Hello

You can try something like this:

```
func stringWithParagraphs() -> NSAttributedString {
    
    let transformers: [TagTransformer] = [
        TagTransformer.brTransformer,
        TagTransformer(tagName: "p", tagType: .start, replaceValue: "\n"),
        TagTransformer(tagName: "p", tagType: .end, replaceValue: "\n")
    ]
    
    let p = Style("p").font(.systemFont(ofSize: 12)).foregroundColor(.red)
    
    return "<p>Sample Text 1</p><p>Sample Text 2</p>"
        .style(tags: p, transformers: transformers)
        .styleAll(Style.font(.boldSystemFont(ofSize: 14)))
        .attributedString
}
```

This will put line break before and after paragraph. If you need some custom logic you may check more flexible TagTransformer init:
`public init(tagName: String, tagType: TagType, transform: @escaping (Tag) -> String)`

**Comment by rafsouzap** [comment]
Tks @psharanda!!
