### ISSUE TITLE
styleMentions returning wrong array detection when used with Korean tags

### ISSUE THREAD

**Issue by manisingh41** [psharanda/Atributika#68]
I have used Atributika Pod in achieving one of the task in my project. I have attributed textview in which mentions, links, hashtags are used. While resetting the attributes of the textview and sending it over the web service I need to extract all the attributed text of the textview which I do using styleMentions(which returns detections array) of Atributika. When mentions are in english it returns one detection for one mention but when Korean mentions are there it returns multiple detections sometimes. Please find textfile attached of the array detections. If you search for the key "mention" you will get 5 results whereas I should have only two one for each mention.

I have used these two lines of code to extract the detections:
let attArray = self.textviewEditMode?.attributedText.styleMentions(.backgroundColor(Fp_s29.color))
let detections = attArray?.detections
whereas,
textviewEditMode- is my UITextview
Fp_s29.color- is my predefined color

Please let me know if something needs to be done. Thank you!

[mentionsDetection.zip](https://github.com/psharanda/Atributika/files/2731682/mentionsDetection.zip)

**Comment by psharanda** [comment]
Hi, please provide your original string

**Comment by manisingh41** [comment]
Hi @psharanda, thanks for your reply. If you check the string like "Hi Dhairya and 새 업무그룹 2". The detections array gives me 5 elements one for "Dhairya" and 4 for "새 업무그룹 2". Ideally it should have been only two, one for each. I think we need to do something with the korean words which creating some issue.
Please let me know in case you need any other detail.

**Comment by psharanda** [comment]
I tried this code
```
func stringWithKoreanNameMention() -> NSAttributedString {
    let s = Style.foregroundColor(.red)
    let a = "Hi @Dhairya and @새업무그룹 2".styleMentions(s)
    print(a.detections.map { $0.type})
    return a.attributedString
}
```
and output looks good for me
`[Atributika.DetectionType.mention("Dhairya"), Atributika.DetectionType.mention("새업무그룹")]`

**Comment by psharanda** [comment]
alright, please provide real string using github code section

**Comment by manisingh41** [comment]
Hi @psharanda, please find working github code mentioned in the link below. It is working similarly to what we have discussed above. We need to rectify for the Korean strings or such similar strings.
Code link: https://github.com/manisingh41/Mention-Hashtags

**Comment by manisingh41** [comment]
Hi @psharanda , did you find any issues?

**Comment by psharanda** [comment]
Hi, i tried to understand what's going on in your project, but it's not easy. Please provide some simple test code (like regular unit test) with your issue reproducible. Even best variant if you can fork this repo, add your test and make PR with failed test.
