### ISSUE TITLE
Support Arbitrary/Custom AttributedStringKey values

### ISSUE THREAD

**Issue by samingle** [psharanda/Atributika#70]
NSAttributedString makes it pretty easy to extend support for custom attributes, but I haven't found a built-in way to apply those attributes out of the box. I was able to extend the Style class to support it pretty easily, but it feels generally useful enough that it'd be valuable as a base level feature for the library. 

here's my extension:
```
extension Style {
    func custom(_ value: Any, _ key: AttributedStringKey, _ type: StyleType = .normal) -> Style {
        return merged(with: Style.custom(value, key, type))
    }
    static func custom(_ value: Any, _ key: AttributedStringKey, _ type: StyleType = .normal) -> Style {
        return Style("", [key: value], type)
    }
}

**Comment by psharanda** [comment]
Hi,
Looks good, thanks!
I think it makes sense for you to create PR, add this extension, write some basic unit test and become proudly member of Atributika contributors :)

**Comment by samingle** [comment]
Will do. Presumably you’d want it as a member of the main style class not an extension in the PR version, right?

**Comment by samingle** [comment]
#71 submitted

**Comment by psharanda** [comment]
thanks!

Atributika (4.6.9) successfully published
