### ISSUE TITLE
UITextView Support

### ISSUE THREAD

**Issue by denniskeithgaso** [psharanda/Atributika#73]
This is really the best attributed string library out there. I wonder if you'd ever support UITextView in the future?

Thanks!
Best regards!

**Comment by psharanda** [comment]
Thanks!
What kind of support do you mean?

**Comment by denniskeithgaso** [comment]
The AttributedLabel class uses UILabel. Will you support UITextView? Like an AttributedTextView.

**Comment by psharanda** [comment]
What exact functionality you would like to have? UITextView is not the best superclass, it is slow and buggy.

**Comment by denniskeithgaso** [comment]
I simple want an editable functionality. But for now, I am using Atributika to create an attributed string for my UITextView. It still works perfectly. However, I cannot add clickable functions to it.

**Comment by psharanda** [comment]
I see, you want it to work like in Notes.app where you can edit contents and click on urls simultaneously. Yeah makes sense. Thanks for your proposal.

**Comment by psharanda** [comment]
From 4.8.0 due to different bugs AttributedLabel uses UITextView instead of UILabel. It is still readonly control, but feel free to experiment

**Comment by psharanda** [comment]
Fixed in 4.8.1

**Comment by Ankish** [comment]
I use this library with native UITextView. I convert HTML string to the attributedstring using this library  and display it in UITextView. For Links like <a> tag I use the tuner.

**Comment by psharanda** [comment]
guess you can try AttributedLabel

**Comment by Ankish** [comment]
Native works great with additional features like drag-drop links etc. I will give it a try though, Thanks!.
There are few sites with HTML links as `<a href=https:>` instead of `<a href=\"https\">`, can you point me the way to handle this link or support if you feel the need?

**Comment by psharanda** [comment]
Yeah true, it looks like this is a valid HTML too. Alright, you can create an issue and I will try to look at it later
