### ISSUE TITLE
Embedded link wrapped in more lines does not detects click everywhere

### ISSUE THREAD

**Issue by zcsipler** [psharanda/Atributika#74]
Nice lib!

If there is an embedded link which is long enough and wrapped to two lines, nothing happens when I click on the last part of the second line. To reproduce the issue pls check the modified demo project here:

https://github.com/zcsipler/Attributika-Link-Issue.git

On the attributed tab I replaced the "link" text to "link that won't detect click here" text in the first cell. Try to click above "here" word, in this case nothing will happen. (Tested in iPhone 8)

**Comment by SamuelSchepp** [comment]
I have the same problem and can reproduce the bug as described.

**Comment by psharanda** [comment]
Appears that in iOS 11, UILabel line break logic was changed. It tries to avoid orphaned words on last line. But NSLayoutManager doesn't. To mimic this we can replace last space with non-breaking space.

**Comment by psharanda** [comment]
Resolved by other approach in 4.8.0 (AttributedLabel is using UITextView instead of UILabel now)
