### ISSUE TITLE
Unable to archive iOS target on Xcode 10.2

### ISSUE THREAD

**Issue by petropavel13** [psharanda/Atributika#75]
Xcode: Version 10.2 (10E125)
[Archive Atributika-iOS_2019-03-27T12-43-58.txt](https://github.com/psharanda/Atributika/files/3012520/Archive.Atributika-iOS_2019-03-27T12-43-58.txt)
Xcode stuck here:
<img width="282" alt="Screenshot 2019-03-27 at 12 49 43" src="https://user-images.githubusercontent.com/6436245/55066420-d32c8880-508e-11e9-9ea3-02793cd53778.png">

**Comment by a-shelyuk** [comment]
The same issue

**Comment by a-shelyuk** [comment]
@petropavel13, I fixed this issue by this:
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == 'Atributika'
                config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
            end
    end
end
```

**Comment by psharanda** [comment]
🎉  Congrats

 🚀  Atributika (4.7.0) successfully published
 📅  March 28th, 01:31
 🌎  https://cocoapods.org/pods/Atributika
 👍  Tell your friends!
