### ISSUE TITLE
Crash in XCode 10.2

### ISSUE THREAD

**Issue by sayler8182** [psharanda/Atributika#76]
After update XCode to 10.2, App crash when I set <a> tag detection

`
"By tapping “Continue” you agree with <a href='https://google.pl'>Terms</a> and <a href='https://google.pl'>Privacy</a>"
            .style(tags: a)
            .styleLinks(a)
            .styleAll(all)
`

<img width="1063" alt="Screen Shot 2019-03-27 at 2 40 15 PM" src="https://user-images.githubusercontent.com/11602110/55080340-50132e80-509e-11e9-8bba-964f679eeab7.png">

Edit:
I've found that ” is the problem

**Comment by hintoz** [comment]
I also have a crash in Xcode 10.2.
```
let labelDanger = Style("span").font(.systemFont(ofSize: 15)).foregroundColor(.red)
let string = "Blablabla \n<span class=\"label label-danger\">qwer</span>"
string.style(tags: [labelDanger]).attributedString
```
![Снимок экрана 2019-03-27 в 19 22 00](https://user-images.githubusercontent.com/1215299/55093578-b19ac380-50c5-11e9-946c-2ff566a35c38.png)

**Comment by artemKatlenok** [comment]
Same here!

**Comment by psharanda** [comment]
OK guys, help is on the way, downloading Xcode

**Comment by hintoz** [comment]
> I also have a crash in Xcode 10.2.
> 
> ```
> let labelDanger = Style("span").font(.systemFont(ofSize: 15)).foregroundColor(.red)
> let string = "Blablabla \n<span class=\"label label-danger\">qwer</span>"
> string.style(tags: [labelDanger]).attributedString
> ```
> ![Снимок экрана 2019-03-27 в 19 22 00](https://user-images.githubusercontent.com/1215299/55093578-b19ac380-50c5-11e9-946c-2ff566a35c38.png)

I realized that this happens with a certain sequence of Cyrillic. Also in some sequence of Cyrillic characters is the following:
![IMG_1447](https://user-images.githubusercontent.com/1215299/55099980-cda46200-50d1-11e9-9445-d5d8b1b20aac.jpeg)

All text should be red.

**Comment by psharanda** [comment]
🎉  Congrats

 🚀  Atributika (4.7.0) successfully published
 📅  March 28th, 01:31
 🌎  https://cocoapods.org/pods/Atributika
 👍  Tell your friends!

**Comment by sayler8182** [comment]
Well done!
