### ISSUE TITLE
Font not applied to strong tag inside paragraph

### ISSUE THREAD

**Issue by margab1** [psharanda/Atributika#88]
For example I have a string `"<p>some string... <strong> string</strong></p>"` and I want to apply different fonts to the paragraph and strong strings. But the paragraph font also applies to the strong tag.

```
let p = Style("p").font(UIFont.init(name: "HelveticaNeue", size: 20)!)
let strong = Style("strong").font(UIFont.init(name: "Copperplate", size: 20)!)
let attr = "<p>some string... <strong> string</strong></p>".(tags: [p,strong]).attributedString
```

Is there any way to have the strong string have a different font,in the above example the Copperplate font?

**Comment by psharanda** [comment]
This doesn't seem an issue any more
