### ISSUE TITLE
issues on xcode9

### ISSUE THREAD

**Issue by tommycloud** [psharanda/Atributika#9]
Hi, I'm using Atributika a while and it's very great, but when I update to xcode 9 there's some error popped up.
Totally 23 issues i'll post some of them below:
Cannot convert value of type '[NSAttributedStringKey : Any]' (aka 'Dictionary<NSString, Any>') to expected argument type '[String : Any]?'

Type 'NSAttributedStringKey' (aka 'NSString') has no member 'font'

Type 'NSAttributedStringKey' (aka 'NSString') has no member 'foregroundColor'

Hope you can get it fixed soon.

Thanks

**Comment by psharanda** [comment]
Please use >4.0 version

**Comment by tommycloud** [comment]
Hi, I'm using 4.1.1, but having no clue about why this happened. 
<img width="1277" alt="2017-10-16 am8 28 34" src="https://user-images.githubusercontent.com/1506047/31590955-51739798-b24c-11e7-96b8-1779c1a59f1a.png">

**Comment by tommycloud** [comment]
Just add Atributika to my test app and still got these errors.

**Comment by psharanda** [comment]
I just created test new app with Xcode 9, cocoapods 1.31, Atributika 4.1.1 and it works fine for me.
Probably you have something wrong with your setup because you are trying to compile swift 4 code with swift 3 compiler.

**Comment by tommycloud** [comment]
Ok, i got it worked, thanks for your help.
