### ISSUE TITLE
Atributika Label auto-size?

### ISSUE THREAD

**Issue by ciathyza** [psharanda/Atributika#92]
How do you make an Atributika label's height auto-size so that it adapts to the text displayed in it?

**Comment by psharanda** [comment]
i use UITextView internally, which supports autosize out of box.

**Comment by palozinski** [comment]
It doesn't work inside in UIScrollView

**Comment by skajake** [comment]
palozinski, just make sure you set .numberOfLines = 0 and it will autosize just fine in a UIScrollView.
