### ISSUE TITLE
Unexpected duplicate tasks: 1) Target 'Atributika' (project 'Pods') has copy command from

### ISSUE THREAD

**Issue by palozinski** [psharanda/Atributika#93]
Hey,

I have with newest Xcode 11 GM 2 Beta:

- removed derived data
- clean build folder

and I have error:

Unexpected duplicate tasks:
1) Target 'Atributika' (project 'Pods') has copy command from '/Users/xxx/code/AppName/Pods/Atributika/Sources/html_specials.plist' to '/Users/xxx/Library/Developer/Xcode/DerivedData/AppName-gzeluvlgsmoczndqfucvblbqtmpm/Build/Products/Alpha-iphonesimulator/Atributika/Atributika.framework/html_specials.plist'
2) Target 'Atributika' (project 'Pods') has copy command from '/Users/xxx/code/AppName/Pods/Atributika/Sources/html_specials.plist' to '/Users/xxx/Library/Developer/Xcode/DerivedData/AppName-gzeluvlgsmoczndqfucvblbqtmpm/Build/Products/Alpha-iphonesimulator/Atributika/Atributika.framework/html_specials.plist'

**Comment by palozinski** [comment]
I have changed minimum deployment target to iOS 11 and works good.

**Comment by psharanda** [comment]
hm, html_specials.plist was removed in latest release

**Comment by palozinski** [comment]
Ahh, this morning I couldn't update to 4.9.0. I don't know why cocoa pods didn't see this update. You are right. Thanks.
