### ISSUE TITLE
How to handle nested tags?

### ISSUE THREAD

**Issue by photos** [psharanda/Atributika#96]
I have the following nested html string:

`<a href=\"https://en.wikipedia.org/wiki/World_of_Dance_(TV_series)\" target=\"_blank\"><strong><em>World of Dance</em></strong></a>`

Expected result:

[**_World of Dance_**](https://en.wikipedia.org/wiki/World_of_Dance_(TV_series))

This is an italicized bold link. How would I handle formatting this? It seems like Style only applies to one tag, but I may be wrong.

**Comment by psharanda** [comment]
Yeah you can't composite font styles using different tag. You need to define font completely. For example:
```
func stringWithBoldItalic() -> NSAttributedString {
    
    let baseFont = UIFont.systemFont(ofSize: 12)
    let descriptor = baseFont.fontDescriptor.withSymbolicTraits([.traitItalic, .traitBold])
    let font = descriptor.map { UIFont(descriptor: $0, size: baseFont.pointSize) } ?? baseFont
    
    let a = Style("a").font(font).foregroundColor(.blue)
    let str = "<a href=\"https://en.wikipedia.org/wiki/World_of_Dance_(TV_series)\" target=\"_blank\">World of Dance</a>".style(tags: a)
        .attributedString
    return str
}
```

**Comment by photos** [comment]
Is there a way or strategy to support multiple styles such as `Style([“b”,”em”])`? If not, this may be a useful feature.

**Comment by psharanda** [comment]
You can create new style from other style using `Style("em", style: otherStyle)` or `otherStyle.named("em")`

**Comment by photos** [comment]
I have created all possible styles for nested HTML tags and have applied it to a string with `string.style(tags:[Style])`. But, when applying these styles, the string is getting overridden and does not respect each style. 

For example, given this HTML snippet:

`<li><a href=\"https://www.youtube.com/watch?v=I_izvAbhExY\" target=\"_blank\"><em>Staying Alive</em></a></li>
<li><a href=\"https://www.youtube.com/watch?v=yca6UsllwYs\" target=\"_blank\"><strong><em>Around the World</em></strong></a></li>
<li><a href=\"https://www.youtube.com/watch?v=mWtIxc38xNE\" target=\"_blank\"><strong>Flashing Lights</strong></a></li>`

Expected Result:

_[Staying Alive](https://www.youtube.com/watch?v=I_izvAbhExY)_
_**[Around the World](https://www.youtube.com/watch?v=yca6UsllwYs)**_
**[Flashing Lights](https://www.youtube.com/watch?v=mWtIxc38xNE)**

Here is my code. Is this properly structured?

`
//<em>
let EmphasisStyle = Style("em").font(ItalicFont).foregroundColor(.black)
//<strong>
let StrongStyle = Style("strong").font(BoldFont).foregroundColor(.black)
//<a>
let LinkStyle = Style("a").font(LinkFont).foregroundColor(.blue,.normal).foregroundColor(.blue,.highlighted)

// <em><strong>
        let StrongEmphasisStyle = Style("em", style: Style("strong")).font(ItalicBoldFont).foregroundColor(.black)
        // <a><strong>
        let LinkEmphasisStyle = Style("em", style: Style("a")).font(ItalicFont).foregroundColor(.blue,.normal).foregroundColor(.blue,.highlighted)
        // <a><strong>
        let LinkStrongStyle = Style("strong", style: Style("a")).font(BoldFont).foregroundColor(.blue,.normal).foregroundColor(.blue,.highlighted)
        // <em><strong><a>
        let LinkStrongEmphasisStyle = Style("em", style: Style("strong", style: Style("a"))).font(ItalicBoldFont).foregroundColor(.blue,.normal).foregroundColor(.blue,.highlighted)

label.attributedText = htmlStr.style(tags: [EmphasisStyle, StrongStyle, LinkStyle, StrongEmphasisStyle, LinkEmphasisStyle, LinkStrongStyle, LinkStrongEmphasisStyle])
`
