### ISSUE TITLE
Handle UIEdgeInsets

### ISSUE THREAD

**Issue by KOSURUUDAYSAIKUMAR** [psharanda/Atributika#97]
While I displayed the data. It gets edges of the text inside. I need to give a gap for top, bottom, left, right.

(https://user-images.githubusercontent.com/28728191/66890584-3cacbe00-f004-11e9-807d-70a6a4b179a7.png)

Can you please help. I tried for the past few days. But the issue not solved.

**Comment by psharanda** [comment]
AttributedLabel is just a wrapper on top of UITextView. So you can work with it as with a standard view.
